### PR TITLE
Testbase improvement

### PR DESCRIPTION
**Pull request by nklymenok**
Add TestBase inheritance from unittest
Refactor TearDownClass and SetUpClassin TestBase

### CODE REVIEW

**Comment by AnastasiiaLatysh** [comment]
i think it's good suggestion! i agree to implement this in our framework

**Review by DmyMi — APPROVED** [review]
looks good, should implement

**Review by olenakhom — APPROVED** [review]
It will be a good idea to add this improvement to our project!

**Review by alianInGitHub — APPROVED** [review]
Finally OK :)

**Pull request merged**
