### PR TITLE
Page object vision

### PR DESCRIPTION
**Pull request by olenakhom**

### CODE REVIEW

**Comment by timbortnik** [comment]
It works!
/EcoMap/github_olena$ nosetests
.
----------------------------------------------------------------------
Ran 1 test in 10.307s

OK

**Review by timbortnik — CHANGES_REQUESTED** [review]
Please gitignore binaries and .idea
Please fix style warnings.
Great to see it working!
image

**Comment by nklymenok** [comment]
I like realization with locators in one file (for each page by class with locators)

**Comment by AnastasiiaLatysh** [comment]
Structured and clear implementation. But I think it would be better to have separate class for BaseTest with setUp and tearDown methods

**Review by timbortnik — APPROVED** [review]

**Review by nklymenok — APPROVED** [review]

**Review by DmyMi — APPROVED** [review]
approved :)

**Comment by nklymenok** [comment]
Great structure!

**Review by alianInGitHub — APPROVED** [review]

**Review by AnastasiiaLatysh — APPROVED** [review]
good implementation )))

**Pull request merged**
